export const SHOW_ERROR_FORMAT = 'SHOW_ERROR_FORMAT';
export const REMOVE_ERROR_FORMAT = 'REMOVE_ERROR_FORMAT';

export const SHOW_ERROR_DATE = 'SHOW_ERROR_DATE';
export const REMOVE_ERROR_DATE = 'REMOVE_ERROR_DATE';

export const SHOW_WRONG_DATES = 'SHOW_WRONG_DATES';
export const REMOVE_WRONG_DATES = 'REMOVE_WRONG_DATES';
